### ISSUE TITLE
build failure with gcc10

### ISSUE THREAD

**Issue by raveit65** [zhuyaliang/user-admin#37]
User-admin failed to build during fedora rawhide (32) mass rebuild because of new gcc 10.
https://koji.fedoraproject.org/koji/taskinfo?taskID=41318895
https://koji.fedoraproject.org/koji/getfile?taskID=41320529&volume=DEFAULT&name=build.log&offset=-4000
```
o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:131: multiple definition of `gnCurrentUserIndex'; src/25a6634@@mate-user-admin@exe/main.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:131: first defined here
/usr/bin/ld: src/25a6634@@mate-user-admin@exe/user-group.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:132: multiple definition of `WindowLogin'; src/25a6634@@mate-user-admin@exe/main.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:132: first defined here
/usr/bin/ld: src/25a6634@@mate-user-admin@exe/user-group.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:131: multiple definition of `gnCurrentUserIndex'; src/25a6634@@mate-user-admin@exe/main.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:131: first defined here
/usr/bin/ld: src/25a6634@@mate-user-admin@exe/user-group.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user-share.h:30: multiple definition of `Change'; src/25a6634@@mate-user-admin@exe/main.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user-share.h:30: first defined here
/usr/bin/ld: src/25a6634@@mate-user-admin@exe/user-history.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:131: multiple definition of `gnCurrentUserIndex'; src/25a6634@@mate-user-admin@exe/main.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:131: first defined here
/usr/bin/ld: src/25a6634@@mate-user-admin@exe/user-history.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user-share.h:30: multiple definition of `Change'; src/25a6634@@mate-user-admin@exe/main.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user-share.h:30: first defined here
/usr/bin/ld: src/25a6634@@mate-user-admin@exe/user-history.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:132: multiple definition of `WindowLogin'; src/25a6634@@mate-user-admin@exe/main.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:132: first defined here
/usr/bin/ld: src/25a6634@@mate-user-admin@exe/user-language.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user-share.h:30: multiple definition of `Change'; src/25a6634@@mate-user-admin@exe/main.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user-share.h:30: first defined here
/usr/bin/ld: src/25a6634@@mate-user-admin@exe/user-language.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:132: multiple definition of `WindowLogin'; src/25a6634@@mate-user-admin@exe/main.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:132: first defined here
/usr/bin/ld: src/25a6634@@mate-user-admin@exe/user-language.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:131: multiple definition of `gnCurrentUserIndex'; src/25a6634@@mate-user-admin@exe/main.c.o:/builddir/build/BUILD/user-admin-1.5.1/x86_64-redhat-linux-gnu/../src/user.h:131: first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.rzVVFT (%build)
    Bad exit status from /var/tmp/rpm-tmp.rzVVFT (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/util.py", line 746, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/mate-user-admin.spec
```
More infos you will find here
https://gcc.gnu.org/gcc-10/porting_to.html#common

PS: I hope everything is fine with you and your family in your country.

**Comment by zhuyaliang** [comment]
@raveit65 Thank you for your modification. I'm sorry that I didn't reply to you in time due to the Spring Festival and the epidemic。I will solve the problem in time
